import React, { useState } from 'react';
import { Calendar, TrendingUp, Smile, Frown, Meh, AlertTriangle, Heart, Plus, FileText } from 'lucide-react';
import { useMood } from '../contexts/MoodContext';
import jsPDF from 'jspdf';

const MoodTracker = () => {
  const { entries, addEntry, loading } = useMood();
  const [selectedMood, setSelectedMood] = useState(null);
  const [note, setNote] = useState('');
  const [showAddEntry, setShowAddEntry] = useState(false);

  const moods = [
    { value: 5, label: 'Excellent', icon: Heart, color: 'text-green-500', bg: 'bg-green-100' },
    { value: 4, label: 'Good', icon: Smile, color: 'text-blue-500', bg: 'bg-blue-100' },
    { value: 3, label: 'Okay', icon: Meh, color: 'text-yellow-500', bg: 'bg-yellow-100' },
    { value: 2, label: 'Not Great', icon: Frown, color: 'text-orange-500', bg: 'bg-orange-100' },
    { value: 1, label: 'Difficult', icon: AlertTriangle, color: 'text-red-500', bg: 'bg-red-100' }
  ];

  const handleSubmit = async () => {
    if (selectedMood === null) return;
    const entry = {
      mood: selectedMood,
      note,
      date: new Date()
    };
    try {
      await addEntry(entry);
      setSelectedMood(null);
      setNote('');
      setShowAddEntry(false);
    } catch (error) {
      console.error("Failed to save mood entry:", error);
    }
  };

  const getAverageMood = () => {
    if (entries.length === 0) return "0.0";
    const sum = entries.reduce((acc, entry) => acc + entry.mood, 0);
    return (sum / entries.length).toFixed(1);
  };

  const getWeeklyData = () => {
    const last7Days = Array.from({ length: 7 }, (_, i) => {
      const date = new Date();
      date.setDate(date.getDate() - i);
      return date.toDateString();
    }).reverse();

    return last7Days.map(dateString => {
      const dayEntries = entries.filter(entry =>
        new Date(entry.date).toDateString() === dateString
      );
      const avgMood = dayEntries.length > 0
        ? dayEntries.reduce((sum, entry) => sum + entry.mood, 0) / dayEntries.length
        : 0;

      return {
        date: dateString,
        mood: avgMood,
        count: dayEntries.length
      };
    });
  };

  const generateMoodPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(16);
    doc.text("Mood Report - Last 7 Days", 20, 20);

    doc.setFontSize(12);
    doc.text("Date", 20, 35);
    doc.text("Avg Mood (/5)", 90, 35);
    doc.text("Entry Count", 150, 35);
    doc.line(20, 38, 190, 38);

    const weekly = getWeeklyData();
    let y = 45;
    weekly.forEach(day => {
      doc.text(day.date, 20, y);
      doc.text(day.mood.toFixed(1), 100, y, { align: "right" });
      doc.text(String(day.count), 160, y, { align: "right" });
      y += 10;
    });

    doc.setFontSize(10);
    doc.text("Generated by Askly Mood Tracker", 20, y + 10);

    doc.save("mood_report.pdf");
  };

  const weeklyData = getWeeklyData();

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      {/* Header with combined buttons */}
      <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6 mb-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="w-12 h-12 bg-gradient-to-br from-orange-500 to-pink-500 rounded-full flex items-center justify-center">
              <TrendingUp className="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-gray-900">Mood Tracker</h1>
              <p className="text-gray-600">Monitor your emotional well-being over time</p>
            </div>
          </div>

          {/* Combined Button Group */}
          <div className="flex gap-2">
            <button
              onClick={generateMoodPDF}
              className="flex items-center space-x-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
            >
              <FileText className="w-4 h-4" />
              <span>Generate Report</span>
            </button>
            <button
              onClick={() => setShowAddEntry(true)}
              className="flex items-center space-x-2 px-4 py-2 bg-orange-600 text-white rounded-lg hover:bg-orange-700 transition-colors"
              disabled={loading}
            >
              <Plus className="w-4 h-4" />
              <span>{loading ? "Loading..." : "Log Mood"}</span>
            </button>
          </div>
        </div>
      </div>

      {/* Mood Statistics Section */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-200">
          <h3 className="text-lg font-medium text-gray-900 mb-2">Average Mood</h3>
          <p className="text-3xl font-bold text-orange-600">{getAverageMood()}/5</p>
        </div>
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-200">
          <h3 className="text-lg font-medium text-gray-900 mb-2">Total Entries</h3>
          <p className="text-3xl font-bold text-blue-600">{entries.length}</p>
        </div>
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-200">
          <h3 className="text-lg font-medium text-gray-900 mb-2">Last Entry</h3>
          <p className="text-xl font-semibold text-gray-800">
            {entries.length > 0 
              ? new Date(entries[entries.length - 1].date).toLocaleDateString() 
              : "None"}
          </p>
        </div>
      </div>

      {/* Recent Entries List */}
      <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6">
        <h3 className="text-lg font-medium text-gray-900 mb-4">Recent Entries</h3>
        {entries.length === 0 ? (
          <p className="text-gray-500">No entries yet. Click "Log Mood" to add one!</p>
        ) : (
          <div className="space-y-4">
            {entries.slice().reverse().map((entry, index) => (
              <div key={index} className="p-4 border border-gray-200 rounded-lg">
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-3">
                    {moods.find(m => m.value === entry.mood)?.icon && (
                      <div className={`p-2 rounded-full ${moods.find(m => m.value === entry.mood).bg}`}>
                        {React.createElement(moods.find(m => m.value === entry.mood).icon, {
                          className: `${moods.find(m => m.value === entry.mood).color} w-5 h-5`
                        })}
                      </div>
                    )}
                    <span className="font-medium">
                      {moods.find(m => m.value === entry.mood)?.label || 'Unknown'}
                    </span>
                  </div>
                  <span className="text-sm text-gray-500">
                    {new Date(entry.date).toLocaleString()}
                  </span>
                </div>
                {entry.note && (
                  <p className="mt-2 text-gray-700">{entry.note}</p>
                )}
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Add Entry Modal */}
      {showAddEntry && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl max-w-md w-full">
            <div className="p-6 border-b border-gray-200">
              <h2 className="text-xl font-semibold text-gray-900">How are you feeling?</h2>
            </div>
            <div className="p-6">
              <div className="mb-6 grid grid-cols-1 gap-3">
                {moods.map((mood) => (
                  <button
                    key={mood.value}
                    onClick={() => setSelectedMood(mood.value)}
                    className={`flex items-center space-x-3 p-4 rounded-lg border-2 transition-colors ${
                      selectedMood === mood.value
                        ? `border-orange-500 ${mood.bg}`
                        : 'border-gray-200 hover:border-gray-300'
                    }`}
                  >
                    <mood.icon className={`w-6 h-6 ${mood.color}`} />
                    <span className="font-medium text-gray-900">{mood.label}</span>
                  </button>
                ))}
              </div>

              <div className="mb-6">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Add a note (optional):
                </label>
                <textarea
                  value={note}
                  onChange={(e) => setNote(e.target.value)}
                  placeholder="What's affecting your mood today?"
                  className="w-full h-24 p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 focus:border-transparent resize-none"
                />
              </div>

              <div className="flex justify-end space-x-3">
                <button
                  onClick={() => {
                    setShowAddEntry(false);
                    setSelectedMood(null);
                    setNote('');
                  }}
                  className="px-4 py-2 text-gray-600 hover:text-gray-800"
                >
                  Cancel
                </button>
                <button
                  onClick={handleSubmit}
                  disabled={selectedMood === null}
                  className="px-6 py-2 bg-orange-600 text-white rounded-lg hover:bg-orange-700 disabled:opacity-50 transition-colors"
                >
                  Save Entry
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default MoodTracker;